SET SQL DIALECT 3; 

CREATE TABLE ASPNETROLE (ID VARCHAR(36) NOT NULL,
        NAME VARCHAR(64) NOT NULL,
        NORMALIZEDNAME VARCHAR(64) NOT NULL,
        CONCURRENCYSTAMP VARCHAR(64),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (NORMALIZEDNAME));

CREATE TABLE ASPNETUSER (ID VARCHAR(36) NOT NULL,
        USERNAME VARCHAR(64) NOT NULL,
        EMAIL VARCHAR(64),
        ACCESSFAILEDCOUNT INTEGER,
        CONCURRENCYSTAMP VARCHAR(64),
        EMAILCONFIRMED CHAR(1),
        LOCKOUTENABLED CHAR(1),
        LOCKOUTEND TIMESTAMP,
        NORMALIZEDEMAIL VARCHAR(64),
        NORMALIZEDUSERNAME VARCHAR(64),
        PASSWORDHASH VARCHAR(128),
        PHONENUMBER VARCHAR(24),
        PHONENUMBERCONFIRMED CHAR(1),
        SECURITYSTAMP VARCHAR(64),
        TWOFACTORENABLED INTEGER,
PRIMARY KEY (ID),
UNIQUE (USERNAME));

ALTER TABLE ASPNETUSER ADD FOREIGN KEY (ROLEID) REFERENCES ASPNETROLE (ID);

CREATE TABLE ASPNETUSERINROLE (USERID VARCHAR(36),
        ROLEID VARCHAR(36),
PRIMARY KEY (USERID,ROLEID));

ALTER TABLE ASPNETUSERINROLE ADD FOREIGN KEY (USERID) REFERENCES ASPNETUSER (ID) ON DELETE CASCADE;
ALTER TABLE ASPNETUSERINROLE ADD FOREIGN KEY (ROLEID) REFERENCES ASPNETROLE (ID) ON DELETE CASCADE;

CREATE TABLE WEATHERSTATION (ID VARCHAR(36) NOT NULL,
        NAME VARCHAR(64) NOT NULL,
        LOCATION VARCHAR(64),
        LATITUDE FLOAT,
        LONGITUDE FLOAT,
        ISPUBLIC CHAR(1),
        HASTEMPERATURE CHAR(1),
        HASPRESSURE CHAR(1),
        HASHUMIDITY CHAR(1),
        HASUV CHAR(1),
PRIMARY KEY (ID),
UNIQUE (NAME));

CREATE TABLE METAINFO (DBREVISION INTEGER NOT NULL);
